# Generated by Django 4.2.7 on 2023-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="DOB",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="gender",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="mobile_no",
            field=models.IntegerField(null=True),
        ),
    ]
